import {api,post} from '../services/api.js';
import {heading,panel,esc,date,human,badge,empty,modal,busy,toast,icon} from '../components/ui.js';
export async function outreach(params){
 const [data,prospects]=await Promise.all([api('/outreach'),api('/prospects')]);
 const rid=params.get('restaurant'),ready=prospects.items.filter(p=>p.can_start&&(!rid||String(p.id)===rid));
 const items=data.items.filter(m=>!rid||String(m.restaurant_id)===rid);
 const scope=prospects.items.find(p=>String(p.id)===rid);
 const mode=params.get('view')||'all',filtered=mode==='review'?items.filter(x=>x.reviewable||x.review_recovery):items;
 const selected=filtered.find(x=>x.id===params.get('message'))||filtered.find(x=>x.reviewable)||filtered[0];
 const target=p=>`#/outreach?${new URLSearchParams({...(rid?{restaurant:rid}:{}),view:mode,message:p.id})}`;
 let message=empty('A little context. A better conversation.','Select a message to see its content and review status.');
 if(selected){const m=selected;message=`<div class="email-head"><div class="message-meta">${badge(m.status)}<span>${esc(human(m.type))} · Revision ${m.revision}</span></div><h2>${esc(m.subject)}</h2><div class="kv"><span>Restaurant</span><a class="text-link" href="#/prospects/${m.restaurant_id}">${esc(m.restaurant)}</a></div><div class="kv"><span>To</span><span>${esc(m.recipient)}</span></div><div class="kv"><span>${m.sent_at?'Sent':'Created'}</span><span>${date(m.sent_at||m.created_at,true)}</span></div></div><div class="email-body">${esc(m.body)}</div><div class="email-actions">${m.recipient_revision?`<small>The contact email changed to ${esc(m.current_recipient)}. A new draft needs your approval.</small><button class="button" id="recipient-revision">Prepare for current email</button>`:m.review_recovery?`<small>${esc(m.read_only_reason)}</small><button class="button" id="retry-review">Prepare for approval</button>`:m.reviewable?`<small>Initial outreach needs your approval.${m.expires_at?`<br>Review expires ${date(m.expires_at,true)}`:''}</small><button class="icon-button" id="regenerate" aria-label="Request changes and regenerate" title="Request changes and regenerate">↻</button><button class="button" id="approve">${icon('check')} Approve & send</button>`:`<small>${esc(m.read_only_reason||'Read-only communication record.')} Delivery links and account credentials are hidden.</small>`}</div>`;}
 return {html:heading('Outreach','Thoughtful messages. One place to review and follow the conversation.',rid?'<a class="button secondary" href="#/outreach">All outreach</a>':'')+
 (scope?`<div class="notice">Showing communication for <strong>${esc(scope.name)}</strong>. ${scope.flags.closed?'This restaurant has opted out; promotional contact is stopped.':''}</div>`:'')+
 (data.runtime_error?`<div class="notice error">${esc(data.runtime_error)}</div>`:'')+
 `<div class="chips"><a class="chip ${mode==='all'?'selected':''}" href="#/outreach?${new URLSearchParams({...(rid?{restaurant:rid}:{}),view:'all'})}">All communication · ${items.length}</a><a class="chip ${mode==='review'?'selected':''}" href="#/outreach?${new URLSearchParams({...(rid?{restaurant:rid}:{}),view:'review'})}">Awaiting review · ${items.filter(x=>x.reviewable||x.review_recovery).length}</a></div>`+
 `<div class="outreach-grid"><section class="panel"><div class="panel-head"><h3>Conversations</h3></div><div class="message-list">${filtered.length?filtered.map(m=>`<a class="message-item ${selected?.id===m.id?'selected':''}" href="${esc(target(m))}"><div class="message-meta">${badge(m.status)}<span>${date(m.created_at)}</span></div><strong>${esc(m.restaurant)}</strong><p>${esc(m.subject)}</p><small class="muted">${esc(human(m.type))}</small></a>`).join(''):empty('No messages here',mode==='review'?'There are no initial messages waiting for review.':'Initial drafts appear automatically after research and qualification. Only qualified prospects with a contact email proceed.')}</div></section><section class="panel">${message}</section></div>`,
 bind(){
 const retryReview=document.querySelector('#retry-review');if(retryReview)retryReview.onclick=()=>busy(retryReview,async()=>{await post(`/outreach/${encodeURIComponent(selected.id)}/retry-review`,{revision:selected.revision});toast('Draft ready. Review it, then approve or request changes.');window.dispatchEvent(new Event('agency-refresh'));});
 const recipientRevision=document.querySelector('#recipient-revision');if(recipientRevision)recipientRevision.onclick=()=>busy(recipientRevision,async()=>{const result=await post(`/outreach/${encodeURIComponent(selected.id)}/recipient-revision`);location.hash=`#/outreach?restaurant=${selected.restaurant_id}&message=${encodeURIComponent(result.message_id)}`;toast('New draft prepared for the current email. Review it before approving.');window.dispatchEvent(new Event('agency-refresh'));});
 const approve=document.querySelector('#approve');if(approve)approve.onclick=()=>busy(approve,async()=>{const result=await post(`/outreach/${encodeURIComponent(selected.id)}/decision`,{decision:'APPROVED',revision:selected.revision});if(result.errors.length)throw new Error(result.errors.join(' '));toast(result.sent?'Email accepted by the provider.':'Approval processed. Sending is not yet confirmed.');window.dispatchEvent(new Event('agency-refresh'));});
 const regen=document.querySelector('#regenerate');if(regen)regen.onclick=()=>{const d=modal(`<div class="modal-head"><h2>What should change?</h2><button class="icon-button" data-close aria-label="Close">×</button></div><p style="font-size:12px;margin-bottom:16px">Your feedback helps the agent write a better draft. The replacement will need your approval.</p><form id="revision-form"><label for="revision-note">Reason for revision</label><textarea id="revision-note" required maxlength="1000" rows="4" placeholder="For example, make the opening more specific and the tone warmer."></textarea><div class="form-actions"><button class="button secondary" data-close type="button">Cancel</button><button class="button" type="submit">↻ Generate revised draft</button></div></form>`);d.querySelector('form').onsubmit=e=>{e.preventDefault();const note=d.querySelector('textarea').value.trim();if(!note)return;busy(e.submitter,async()=>{const result=await post(`/outreach/${encodeURIComponent(selected.id)}/decision`,{decision:'REJECTED',note,revision:selected.revision});if(result.errors.length)throw new Error(result.errors.join(' '));d.close();toast('Revised draft requested. Review the new version.');location.hash=`#/outreach?restaurant=${selected.restaurant_id}&view=review`;window.dispatchEvent(new Event('agency-refresh'));});};};}};
}
