import {api,post} from '../services/api.js';
import {heading,panel,restaurant,badge,esc,date,human,icon,empty,modal,busy,toast,kv,lifecycle,trial} from '../components/ui.js';
// The restaurant just clicked in the Prospects list: its page starts the workflow once. Not stored, so a page
// reload or the automatic refresh never starts (and pays for) a run again.
let startOnOpen=null;
const filters={all:'All prospects',qualified:'Qualified',awaiting_approval:'Awaiting approval',outreach_sent:'Outreach sent',waiting_response:'Waiting for response',interested:'Interested',strategy:'Strategy',active_client:'Active client',free_trial:'Free trial',feedback_due:'Feedback due',closed:'Closed',followup_due:'Follow-up due',trial_ending:'Trial ending soon',attention:'Needs attention',analysis_failed:'Analysis failed'};
export async function prospects(params){
 const {items,updated_at}=await api('/prospects');
 return {html:heading('Prospects','The right context for every relationship.',`<button class="button" id="add-prospect">+ Add prospect</button>`)+
 `<div class="toolbar"><div class="search">${icon('search')}<input id="search" aria-label="Search prospects" placeholder="Search restaurant, Instagram or email"></div><select id="filter" aria-label="Filter prospects">${Object.entries(filters).map(([key,label])=>`<option value="${key}" ${params.get('filter')===key?'selected':''}>${label}</option>`).join('')}</select><select id="sort" aria-label="Sort prospects"><option value="created_at">Recently added</option><option value="last_contact">Recently contacted</option><option value="next_contact">Follow-up due</option><option value="trial">Trial ending soon</option></select></div>`+
 `<section class="panel"><div class="panel-head"><h3>Restaurant directory</h3><span id="result-count" class="count-label"></span></div><div id="prospect-table"></div></section>`,updated:updated_at,
 bind(){const search=document.querySelector('#search'),filter=document.querySelector('#filter'),sort=document.querySelector('#sort');
 const render=()=>{let data=items.filter(p=>(filter.value==='all'||p.flags[filter.value])&&[p.name,p.instagram,p.email].some(x=>(x||'').toLowerCase().includes(search.value.toLowerCase())));
 data.sort((a,b)=>{const key=sort.value;if(key==='next_contact'||key==='trial'){const av=key==='trial'?a.trial?.end:a.next_contact,bv=key==='trial'?b.trial?.end:b.next_contact;return (av?Date.parse(av):Infinity)-(bv?Date.parse(bv):Infinity);}return Date.parse(b[key]||0)-Date.parse(a[key]||0);});
 document.querySelector('#result-count').textContent=`${data.length} of ${items.length} prospects`;
 document.querySelector('#prospect-table').innerHTML=data.length?`<div class="table-wrap"><table><thead><tr><th>Restaurant</th><th>Lifecycle</th><th>Status</th><th>Next action</th><th>Trial / timing</th><th></th></tr></thead><tbody>${data.map(p=>`<tr><td>${restaurant(p)}<span class="subline">${esc(p.email||'Email not added')}</span></td><td>${esc(p.stage)}<span class="mini-lifecycle" aria-label="Lifecycle progress">${p.lifecycle.map(step=>`<i class="${esc(step.state)}" title="${esc(step.label)}: ${esc(human(step.state))}"></i>`).join('')}</span></td><td>${badge(p.status)}</td><td>${esc(p.next_action)}<span class="subline">${p.location?esc(p.location):'Location not added'}</span></td><td>${p.trial?`${p.trial.days_remaining} days remaining<span class="subline">Ends ${date(p.trial.end)}</span>`:p.next_contact?`${date(p.next_contact)}<span class="subline">Next contact</span>`:'<span class="muted">—</span>'}</td><td><a class="text-link" href="#/prospects/${p.id}" aria-label="Open ${esc(p.name)}">${icon('arrow')}</a></td></tr>`).join('')}</tbody></table></div>`:empty(items.length?'No matching prospects':'Your next relationship starts here',items.length?'Try another search or filter.':'Add a restaurant to start research and qualification.');};
 document.querySelector('#prospect-table').onclick=e=>{const a=e.target.closest('a[href^="#/prospects/"]');if(a)startOnOpen=a.getAttribute('href').split('/').pop();};
 search.oninput=render;filter.onchange=render;sort.onchange=render;render();document.querySelector('#add-prospect').onclick=()=>addProspect(items);if(params.get('add'))addProspect(items);}};
}
function addProspect(items){
 const d=modal(`<div class="modal-head"><div><div class="eyebrow">GROW YOUR WORKSPACE</div><h2>Add a prospect</h2></div><button class="icon-button" data-close aria-label="Close">×</button></div><p style="font-size:12px;margin-bottom:18px">Existing restaurants are already in your workspace. Find one below, or add a new restaurant.</p><input id="existing-search" placeholder="Find an existing restaurant" aria-label="Find existing restaurant"><div id="existing-results" style="max-height:145px;overflow:auto;margin-bottom:20px"></div><form id="add-form"><div class="form-grid"><div class="full"><label for="name">Restaurant name</label><input id="name" name="name" required maxlength="255"></div><div><label for="instagram">Instagram username</label><input id="instagram" name="instagram_username" required maxlength="30" placeholder="@restaurant"></div><div><label for="email">Contact email</label><input id="email" name="email" type="email" required maxlength="255"></div><div class="full"><label for="location">Location</label><input id="location" name="location" maxlength="255" placeholder="City, area"></div></div><p id="form-error" role="alert"></p><div class="form-actions"><button type="button" class="button secondary" data-close>Cancel</button><button class="button" type="submit">Add prospect</button></div></form>`);
 const search=d.querySelector('#existing-search'),render=()=>{const value=search.value.toLowerCase();d.querySelector('#existing-results').innerHTML=items.filter(p=>[p.name,p.instagram,p.email].some(x=>(x||'').toLowerCase().includes(value))).slice(0,4).map(p=>`<a class="existing-result" href="#/prospects/${p.id}">${esc(p.name)}<small>@${esc(p.instagram)} · ${esc(p.stage)}</small></a>`).join('');d.querySelectorAll('.existing-result').forEach(a=>a.onclick=()=>d.close());};search.oninput=render;render();
 d.querySelector('#add-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;const values=Object.fromEntries(new FormData(e.target));for(const k of ['email','location'])if(!values[k])values[k]=null;try{const result=await post('/api/restaurants?autostart=true',values);d.close();location.hash=`#/prospects/${result.id}`;toast('Prospect added. Research, qualification and draft preparation will run automatically.');}catch(error){d.querySelector('#form-error').textContent=error.message;}finally{b.disabled=false;}};
}
export async function detail(id){
 const p=await api(`/prospects/${id}`);
 const link=(to,label)=>`<a class="text-link" href="#/${to}">${label} ↗</a>`;
 // Same layout as the qualification panel: key numbers as badges, then the observations as numbered rows that scroll.
 const obs=p.research.observations;
 const research=p.research.date?`<div class="panel-body"><div class="decision">${Object.entries(p.research.metrics).map(([k,v])=>`<span class="badge neutral">${esc(k)} <b>${esc(typeof v==='number'?v.toLocaleString('en-US'):v)}</b></span>`).join('')}<small class="muted">${obs.length} observation${obs.length===1?'':'s'}</small></div><div class="gap-list">${obs.map((x,i)=>`<div class="obs-row"><span class="gap-rank">${i+1}</span><p>${esc(x)}</p></div>`).join('')}</div><small class="muted">Research completed ${date(p.research.date)}</small></div>`:empty('Research is not complete','New prospects are researched and qualified automatically. A qualified prospect’s first draft waits for your approval.');
 const q=p.qualification_detail;
 const severity=s=>`<span class="badge ${/high|critical/i.test(s)?'bad':/moderate|medium/i.test(s)?'warn':'neutral'}">${esc(s||'Unrated')}</span>`;
 const list=(title,items)=>items.length?`<div class="gap-label">${esc(title)}</div><ul class="observations">${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'';
 const source=b=>b.url&&/^https?:\/\//.test(b.url)?` <a class="text-link" href="${esc(b.url)}" target="_blank" rel="noopener noreferrer">Source ↗</a>`:'';
 // Each gap is a one-line summary (number, name, severity) that opens to its details; the list scrolls inside the panel.
 const gapCard=(g,i)=>`<details class="gap-card"><summary class="gap-head"><span class="gap-rank">${i+1}</span><h4>${esc(g.gap)}</h4>${severity(g.severity)}${g.confidence?`<span class="badge neutral">${esc(g.confidence)} confidence</span>`:''}</summary><div class="gap-body">${g.description?`<p>${esc(g.description)}</p>`:''}${list('Evidence',g.evidence)}${g.benchmarks.length?`<div class="gap-label">Benchmark</div><ul class="observations">${g.benchmarks.map(b=>`<li>${esc(b.text)}${source(b)}</li>`).join('')}</ul>`:''}${g.rationale?`<div class="gap-label">Why it matters</div><p>${esc(g.rationale)}</p>`:''}</div></details>`;
 const qualified=q?`<div class="panel-body"><div class="gap-list">${q.gaps.map(gapCard).join('')}</div><small class="muted">Qualification completed ${date(q.date)}</small></div>`:empty('Qualification is not complete','The Qualification Agent reviews the research and lists the marketing gaps it finds.');
 // Offer the analysis when it failed, or when there is no qualification yet and nothing is running
 // (autostart only happens when a prospect is added, so a restaurant whose runs were removed needs this button).
 // Start only a restaurant that has never been analyzed: no research, no qualification and nothing running.
 const needsRun=!p.flags.closed && !p.research_run_id && !p.qualification_run_id && !['running','queued'].includes(p.analysis_status);
 return {html:heading(p.name,`@${p.instagram} · ${p.email||'Email not added'}${p.location?' · '+p.location:''}`,`<a class="button secondary" href="#/prospects">← All prospects</a>`,'PROSPECT PROFILE')+
 (p.flags.closed?'<div class="notice">This restaurant has opted out. Promotional outreach is stopped.</div>':'')+
 panel('Relationship journey',lifecycle(p)+`<div class="panel-body"><strong>Next: ${esc(p.next_action)}</strong><p>Research → Qualification → Draft preparation runs automatically. The first email is sent only after your approval.</p></div>`,badge(p.stage))+
 `<div class="detail-grid"><div>${panel('Restaurant & qualification',`<div class="panel-body">${kv('Restaurant',p.name)}${kv('Instagram','@'+p.instagram)}${kv('Email',p.email)}${kv('Location',p.location)}<div class="kv"><span>Qualification</span>${badge(p.qualification)}</div>${kv('Next action',p.next_action)}${p.analysis_status?`<div class="notice">Analysis: ${esc(human(p.analysis_status))}</div>`:''}<div class="form-actions"><button class="button secondary" id="edit-contact">Edit contact</button></div></div>`)}
 ${panel('Research summary',research)}
${panel('Qualification & marketing gaps',qualified)}
 </div><div>${panel('Communication',`<div class="panel-body"><div class="kv"><span>Response</span>${badge(p.response)}</div>${kv('Follow-ups sent',p.followup_attempts)}${kv('Last contact',date(p.last_contact))}${kv('Last response',date(p.last_response))}${kv('Next follow-up',date(p.next_contact))}<a class="button secondary" style="width:100%;margin-top:15px" href="#/outreach?restaurant=${p.id}">Open outreach workspace</a></div>`)}
 ${panel('30-day free trial',`<div class="panel-body">${trial(p)}</div>`)}
 ${panel('Relationship timeline',p.timeline.length?`<div class="panel-body">${p.timeline.map(t=>`<div class="timeline-row"><small>${date(t.at,true)}</small>${t.href?`<a class="text-link" href="${esc(t.href)}">${esc(t.title)} ↗</a>`:`<strong>${esc(t.title)}</strong>`} <span>${badge(t.status)}</span></div>`).join('')}</div>`:empty('No activity yet','Research, communication and relationship events will appear as they happen.'))}
 ${p.relevant_events.length?panel('Relevant occasions',`<div class="panel-body">${p.relevant_events.map(x=>`<p>${esc(x)}</p>`).join('')}<small>Context selected for previous outreach.</small></div>`):''}</div></div>`,
 bind(){if(startOnOpen===String(p.id)){startOnOpen=null;if(needsRun)post(`/api/restaurants/${p.id}/analyze`).then(()=>{toast('Workflow started: research, then qualification. Progress updates automatically.');window.dispatchEvent(new Event('agency-refresh'));}).catch(e=>toast(e.message));}
 document.querySelector('#edit-contact').onclick=()=>{const d=modal(`<div class="modal-head"><h2>Contact details</h2><button class="icon-button" data-close aria-label="Close">×</button></div><form id="edit-form"><label for="contact-email">Email</label><input id="contact-email" type="email" name="email" value="${esc(p.email||'')}"><label for="contact-location" style="margin-top:15px">Location</label><input id="contact-location" name="location" value="${esc(p.location||'')}"><div class="form-actions"><button class="button" type="submit">Save details</button></div></form>`);d.querySelector('form').onsubmit=e=>{e.preventDefault();busy(e.submitter,async()=>{const values=Object.fromEntries(new FormData(e.target));for(const key of ['email','location'])if(!values[key])values[key]=null;await api(`/api/restaurants/${p.id}?autostart=true`,{method:'PATCH',body:JSON.stringify(values)});d.close();toast('Contact details updated.');window.dispatchEvent(new Event('agency-refresh'));});};};}};
}
