// strategy-pdf.js is loaded only when a PDF is requested: a missing or broken file must not blank the whole workspace.
async function downloadStrategyPdf(strategy){const {downloadStrategyPdf:download}=await import('./strategy-pdf.js');return download(strategy);}
import {api,post} from '../services/api.js';
import {heading,panel,restaurant,esc,date,badge,empty,kv,modal,busy,toast} from '../components/ui.js';
export async function strategies(params){
 const {items}=await api('/prospects'),rid=params.get('restaurant');
 const rows=items.filter(p=>(p.strategy_id||p.strategy_request_status||p.flags.interested)&&(!rid||String(p.id)===rid));
 return {html:heading('Strategies','From a positive response to a plan ready to put into action.',rid?'<a class="button secondary" href="#/strategies">All strategies</a>':'')+
 (rows.length?`<div class="strategy-grid">${rows.map(p=>`<section class="panel strategy-card">${restaurant(p)}${kv('Strategy request',p.strategy_request_status||'Not created')}${kv('Generation',p.strategy_id?'Saved plan available':'Awaiting agent output')}${kv('Delivery',p.strategy_delivered?'Provider accepted':'Not confirmed')}<div style="margin-top:12px">${badge(p.stage)}</div>${p.strategy_id?`<button class="button secondary" data-plan="${p.id}">View strategy ↗</button> <button class="button secondary" data-pdf="${p.id}">Download PDF</button>`:`<a class="button secondary" href="#/prospects/${p.id}">View relationship</a>`}</section>`).join('')}</div>`:empty('The next chapter starts with “Yes”','Strategy requests appear here after a restaurant expresses interest. Existing saved strategies are shown here too.')),
 bind(){document.querySelectorAll('[data-pdf]').forEach(b=>b.onclick=()=>busy(b,async()=>{const s=await api(`/api/restaurants/${b.dataset.pdf}/agent-strategy`);await downloadStrategyPdf(s);}));document.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>busy(b,async()=>{const s=await api(`/api/restaurants/${b.dataset.plan}/agent-strategy`);modal(`<div class="modal-head"><div><div class="eyebrow">SAVED STRATEGY</div><h2>${esc(s.restaurant_name)}</h2></div><button class="icon-button" data-close aria-label="Close">×</button></div><p>${esc(s.summary||s.focus||'')}</p>${s.targets?.length?`<ul class="observations">${s.targets.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`:''}<div style="margin-top:18px">${(s.days||[]).map(day=>`<div class="plan-day"><span class="day">Day ${day.day}</span><div><h4>${esc(day.focus||day.title||day.task||day.content_type||'Planned activity')}</h4><p>${esc(day.description||day.action||day.instructions||'')}</p>${badge(day.status||'Planned')}</div></div>`).join('')}</div>`);}));}};
}
export async function feedback(params){
 const d=await api('/feedback'),rid=params.get('restaurant');
 const rows=d.items.filter(x=>!rid||String(x.restaurant_id)===rid),issues=d.issues.filter(x=>!rid||String(x.restaurant_id)===rid);
 return {html:heading('Feedback & relationships','Listen to the experience. Follow through where it matters.',rid?'<a class="button secondary" href="#/feedback">All feedback</a>':'')+
 `<div class="two-col">${panel('Restaurant feedback',rows.length?rows.map(x=>`<article class="feedback-item"><div class="meta"><a class="text-link" href="#/prospects/${x.restaurant_id}">${esc(x.restaurant)}</a>${x.rating?`<span class="badge">${x.rating} / 5</span>`:''}</div><blockquote>${esc(x.message)}</blockquote><small>${date(x.date,true)} · ${esc(x.source)} · Received</small></article>`).join(''):empty('Room for honest feedback','Feedback submitted through the restaurant interface will appear here.'))}
 ${panel('Issues requiring attention',issues.length?issues.map(x=>`<article class="feedback-item"><div class="meta"><a class="text-link" href="#/prospects/${x.restaurant_id}">${esc(x.restaurant)}</a>${badge(x.status)}</div><blockquote>${esc(x.reason)}</blockquote><small>${date(x.date)} · ${esc(x.severity)}</small>${!['RESOLVED','CLOSED'].includes(x.status)?`<div class="form-actions"><button class="button secondary" data-resolve="${esc(x.id)}">Mark resolved</button></div>`:''}</article>`).join(''):empty('No open issues','Escalated client issues will appear here for your team.'))}</div>`,
 bind(){document.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=()=>busy(b,async()=>{await post(`/issues/${encodeURIComponent(b.dataset.resolve)}/resolve`);toast('Issue marked resolved.');window.dispatchEvent(new Event('agency-refresh'));}));}};
}
