export const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={dashboard:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',prospects:'<path d="M3 21V7l9-4 9 4v14M3 11h18M9 21v-6h6v6M7 7v4M12 5v6M17 7v4"/>',outreach:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',strategies:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',feedback:'<path d="M21 11a8 8 0 0 1-8 8H6l-4 3V11a9 9 0 0 1 19 0Z"/><path d="M7 10h10M7 14h6"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',check:'<path d="m5 12 4 4L19 6"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>'};
export const icon = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.clock}</svg>`;
export const human = s => String(s||'Not started').toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
export const date = (s, time=false) => {if(!s)return '—';const d=new Date(s);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',...(time?{hour:'2-digit',minute:'2-digit'}:{})});};
export function badge(s){const v=String(s||'NOT_STARTED').toUpperCase();let color=/FAILED|ERROR|NOT_INTERESTED|DO_NOT_CONTACT|CLOSED_LOST/.test(v)?'bad':/APPROVAL|GENERATED|DUE|WAITING|PENDING/.test(v)?'warn':/SENT|DELIVERED|COMPLETED|ACTIVE|READY|QUALIFIED|INTERESTED|APPLIED|APPROVED/.test(v)&&!v.startsWith('NOT_')?'good':'neutral';return `<span class="badge ${color}">${esc(human(s))}</span>`;}
export const restaurant = p => `<a class="restaurant" href="#/prospects/${p.id}"><span class="initial">${esc(p.name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase())}</span><span><strong>${esc(p.name)}</strong><small>@${esc(p.instagram||'')}</small></span></a>`;
export const empty=(title,text,action='')=>`<div class="empty"><div class="empty-icon">✦</div><h3>${esc(title)}</h3><p>${esc(text)}</p>${action}</div>`;
export const heading=(title,subtitle,action='',eyebrow='AGENCY WORKSPACE')=>`<div class="page-heading"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div>${action}</div>`;
export const panel=(title,body,link='')=>`<section class="panel"><div class="panel-head"><h3>${esc(title)}</h3>${link}</div>${body}</section>`;
export const kv=(label,value)=>`<div class="kv"><span>${esc(label)}</span><span>${esc(value??'—')}</span></div>`;
export const lifecycle=p=>`<div class="lifecycle">${p.lifecycle.map(s=>`<div class="step ${esc(s.state)}"><span class="dot">${s.state==='completed'?'✓':s.state==='current'?'●':'○'}</span>${esc(s.label)}<small>${esc(human(s.state))}</small></div>`).join('')}</div>`;
export function trial(p){const t=p.trial;if(!t)return `<p class="muted">${p.strategy_delivered?'Waiting for the restaurant to activate its account.':'The trial begins on the first successful dashboard sign-in.'}</p>`;return `<div class="trial"><div class="trial-heading"><div><b>${t.current_day}</b><span> / ${t.total_days} days</span></div>${badge(t.status)}</div><div class="bar" role="progressbar" aria-label="Trial elapsed" aria-valuenow="${t.percent}" aria-valuemin="0" aria-valuemax="100"><i style="width:${t.percent}%"></i></div><strong>${t.days_remaining} days remaining</strong>${kv('Activated',date(t.start))}${kv('Ends',date(t.end))}${kv('Feedback due',date(t.feedback_due_at))}</div>`;}
export function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('visible'),6000);}
export function modal(html){const d=document.querySelector('#dialog');d.innerHTML=`<div class="modal-body">${html}</div>`;d.showModal();d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.close());return d;}
export async function busy(button,fn){button.disabled=true;window.agencyBusy=(window.agencyBusy||0)+1;try{await fn();}catch(e){toast(e.message);}finally{window.agencyBusy--;if(button.isConnected)button.disabled=false;}}
